### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#1]
In response to:
https://github.com/wtsi-hgi/cookie-monster/blob/develop/requirements.txt#L4

That library backports `typing` to versions of Python previous to 3.5. As we use enums (introduced in Python 3.4) without similar backporting, `mypy-lang` effectively only adds support for Python 3.4. This was however what was required a few weeks ago as the production environment then only had 3.4. Since then 3.5 has been installed.

Question: do we still need to support 3.4? If not, we can drop the `mypy-lang` requirement.

**Comment by Xophmeister** [comment]
If 3.5 is available on the target host, I vote to remove the `mypy-lang` dependency
