### ISSUE TITLE
Legacy confusion - stale things in `BiscuitTin`

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#15]
There are some legacy comments/code in `Ernie` that are now a bit misleading since we changed from `Metadata` to `Enrichment`. I was confused for a while with `Ernie.add_metadata`, which takes an argument of type `Enrichment`. It's also doesn't align with `Ernie.get_metadata`, which returns an iterable of `Metadata` instances.

**Comment by Xophmeister** [comment]
I suppose metadata is a collection of enrichments, so `get_metadata` still makes sense. However, `add_metadata` should probably be `enrich`.
