### ISSUE TITLE
Remove coupling of `Cookie` to iRODS  

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#16]
Each Cookie holds an the identifier of the data object to which the Cookie relates to. The implementation implies this must be a "path" (because we're using the iRODS path as the identifier) but it could be anything (e.g. a checksum in an object store).

**Comment by Xophmeister** [comment]
One thing to note about this: Using the more generic `identifier` (or whatever) is a good idea, but it runs a possible risk of clashes. For example, the checksum of two different objects on two different object stores could potentially be the same. Thus you would need to namespace them somehow; either embedded in the identifier (like the scheme in URLs), or with an additional attribute(*).

(*) Potentially, the `source` attribute could provide enough information to distinguish this.

**Comment by colin-nolan** [comment]
To say that object `a` is different to object `z` (in a different object store or not) means that there must be a way of distinguishing the objects, e.g. there exist a function `id(x)` where `a == z <=> id(a) == id(z)`. In the example you give, although the checksums that each object store calculates cannot be used, there must exist `id` (even if it's `id(x) = x`) else you couldn't say `a != z`.

Namespacing identiers doesn't make sense, except for in the case `Ɐa∈A,z∈Z: id(a) != id(z)`. This is because it would be possible for an object to have the same identier in more than one namespace. If this is not possible and `id` uses namespaces to stop collisions, then it should be questioned why the same Cookie jar is used to store information about 2 completely independent sets of things...

**Comment by jrandall** [comment]
Perhaps using URIs for these identifiers would be appropriate? While it is true that you could have many URI that point to an "equivalent" object, they really aren't the same resource if they held in two different systems (even if they are related by virtue of one being a copy of the other), especially when those systems hold different metadata about them. 

There is at present no standard URI scheme for iRODS, but we have an open issue in htslib to propose one (https://github.com/samtools/htslib/issues/229). Maybe cookie-monster should jump on that bandwagon? 

I would point out that depending on what it is exactly that you are identifying, RFC6920 (http://tools.ietf.org/html/rfc6920) might be relevant as well.

**Comment by Xophmeister** [comment]
I agree: We're not in the business of what amounts to deduplication based on source. One could argue, by virtue of its quantisation, all data is countably infinite, so necessarily (and sufficiently) has at least once bijection with the natural numbers: Any of these would make a fine identity function, in terms of strict technical requirements; however, my point is that `irods://path/to/my/file`, for example, has certain UX benefits, not to mention being trivial to implement.

**Comment by colin-nolan** [comment]
https://github.com/wtsi-hgi/cookie-monster/commit/641d61773ef2d51132cd27a9f538a18815e4ce61 removes the coupling of Cookies to iRODS paths, closing this ticket.

The ticket for the change in the identifier we use in the our particular setup is found here: https://github.com/wtsi-hgi/hgi-cookie-monster/issues/2.
