### ISSUE TITLE
Log to InfluxDB

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-hgi/cookie-monster#20]
Allow logging data to be written to InfluxDB

**Comment by colin-nolan** [comment]
Link from Emyr to internal wiki on the subject: http://mediawiki.internal.sanger.ac.uk/index.php/Metrics_and_Monitoring.

**Comment by Xophmeister** [comment]
Since reading this documentation, plus looking at [InfluxDB-Python](http://influxdb-python.readthedocs.org/en/stable/), it would appear that logging into InfluxDB should be more "curated" than what Python's logging spews out. Moreover, ideally, it should be numeric data (or, at worst, enumerated constants).

I propose we therefore have a new module that hooks into other modules and reports statistics downstream to InfluxDB -- similar to how Elmo, the HTTP API module, works -- rather than just effectively redirecting stdout into InfluxDB.

What metrics are worth logging? Ideas:
* Current processing queue length;
* Total updates retrieved and/or processed;
* Rule hit rate;
* Resource consumption of application and/or DB servers;

...these ought to be run periodically or on change, if we can detect such things.

**Comment by colin-nolan** [comment]
Other ideas:
- Information about number of updates coming from iRODS.
- Time taken to enrich Cookies upon retrieval.
- Time taken to process Cookies.
- Actions performed by the CookieJar (number of enrichments, completed, failed, etc.)

**Comment by colin-nolan** [comment]
Closed in https://github.com/wtsi-hgi/cookie-monster/commit/e87aa5c034d549dca87b28af570554053880fa6a.
