### ISSUE TITLE
Expected `BiscuitTin` to notify listeners upon requeue

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#22]
This line in the `BiscuitTin` test module indicates that `BiscuitTin` does not notify listeners when Cookie is requeued after failure: https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/tests/cookiejar/test_biscuit_tin.py#L213

**Comment by Xophmeister** [comment]
It does, but it's delayed because of the "passive" queues. I believe this has been discussed several times before. See, for instance, https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/cookiejar/biscuit_tin.py#L86-L87

**Comment by colin-nolan** [comment]
The assertion is wrong then. It just happens to pass because the watcher has yet to poll and discover the change.

**Comment by colin-nolan** [comment]
As acknowledged by the code comment, the assertion here is also wrong for the same reason:
https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/tests/cookiejar/test_biscuit_tin.py#L241
