### ISSUE TITLE
`BiscuitTin` tests failing

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#26]
I'm now observing that the tests for `BiscuitTin` are failing all of the time (they appeared to work sporadically yesterday).

Example `test09_out_of_order_enrichment`:
```
Actual: { source: random, metadata: {'xyzzy': 123}, timestamp: 1981-09-25 04:55:00+00:00 }
Expected: { source: random, metadata: {'xyzzy': 123}, timestamp: 1981-09-25 05:55:00 }
```

Tests 2, 3, 5, 9, 11 are also failing

**Comment by Xophmeister** [comment]
I've been unable to replicate these problems, but 68a12cd may help resolve them for you, as the timezone is now explicitly declared in the test items.

**Comment by colin-nolan** [comment]
Cheers - that appears to have resolved the issue.
