### ISSUE TITLE
Stop giving listeners on `CookieJar` the number of Cookies to process 

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#28]
This information is unused and requires an extra call to `queue_length` to acquire.

**Comment by Xophmeister** [comment]
What data should the listeners be called with? Anything?

**Comment by colin-nolan** [comment]
I don't think they need anything.

**Comment by Xophmeister** [comment]
Yep: Just the broadcast is enough to indicate there is something to do...
