### ISSUE TITLE
Multiple calls to `enrich_cookie` for the same cookie after retrieve

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#3]
Retrieving updates from iRODS can return multiple updates that relate to the same entity, e.g. if many metadata operations occur, you get a separate `Update` for each. These updates cannot be merged (at least not with are current `Update` model) without throwing away timestamps.

The problem is that when an update about an entity is given to `CookieJar` via the `enrich_cookie` method, `CookieJar` flags it as dirty straight away and processing will begin. However, a moment later, another update may be fed in about the same cookie: it is marked as dirty and is processed yet again. Therefore, the same cookie may be processed any number of times after a single retrieve.

**Comment by colin-nolan** [comment]
Options:
- Merge updates relating to the same iRODS entity (cookie), throwing out all but oldest/newest timestamps.
- Modify `Update` such that all the data about a cookie can be combined and no timestamps forgotten.
- Modify the expected behaviour of `CookieJar` implementations so `mark_as_dirty` is not triggered automatically upon `enrich_cookie`.
- `enrich_cookie` "transaction"?
- Other?

**Comment by Xophmeister** [comment]
I'm not sure if I'd class this as a bug: that's how it's designed to work. Wouldn't it make sense for any upstream retrieval to aggregate metadata before passing it to `enrich_cookie`?

**Comment by colin-nolan** [comment]
Yea, it might not be a bug but it's not desirable behaviour. To aggregate upstream (the way things currently are) requires timestamps to be thrown away). Is this the best way solution?

Related: https://github.com/wtsi-hgi/cookie-monster/issues/4

**Comment by Xophmeister** [comment]
Presumably the timestamps of disparate updates within the same update would be relatively close together (within the retrieval period, except for the first one)? Either way, I don't think it matters too much if they're thrown away, save the latest. The timestamp isn't used in any meaningful way, it's just helpful for backtracking.

**Comment by colin-nolan** [comment]
I agree: I shall just keep the latest.

**Comment by colin-nolan** [comment]
Resolved in https://github.com/wtsi-hgi/cookie-monster/commit/611cb8b512b479faed15ec9701f50f467395c6ac.
