### ISSUE TITLE
Make BiscuitTin block on unresponsive DB requests

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-hgi/cookie-monster#30]
`BiscuitTin` is designed to requeue upserts in the event of an unresponsive CouchDB. However, all other DB operations will raise an exception, which will bubble up and crash the Monster... Make other DB requests (i.e., all calls to `_SofterCouchDB` methods in `Sofabed` and `_DesignDocument`) block if the DB is unresponsive until it is able to fulfil its request.

**Comment by colin-nolan** [comment]
This could be achieved through another `CookieJar` decorator - a `FailfreeCookieJar`.

**Comment by Xophmeister** [comment]
A "gotta catch'em all exceptions decorator" might be worthwhile, in a general sense -- I've certainly used that pattern before -- but I think the specific methods called by `BiscuitTin` need to be more robust in this regard. (Indeed, I was unsure as to whether I ought to mark this as an enhancement or a bug.)

There is a general question about how to recover from failure: Keep trying, ad infinitum, even if the failure condition is never resolved (or unresolvable; e.g., if the database goes away, the heat death of the Universe, etc.); or whether it should give up and crash after a reasonable amount of trying, however that's defined... I'm inclined towards the latter. (In fact, I'm inclined towards failing as early as possible, but Python isn't Erlang and we need to make compromises, I suppose!)
