### ISSUE TITLE
Processor may process the same cookie in parallel

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#4]
`CookieJar` does not prevent the same cookie from being processed in parallel. This can lead to the same cookie enrichment to be loaded (a potentially very expensive operation!) more than once.

**Comment by Xophmeister** [comment]
Once a cookie has been returned by `get_next_for_processing`, it is marked as in progress in the underlying database. Once this is set, it is dropped from the queue and it's not possible to get at it directly. The only way you could process the same cookie concurrently is if you *purposely* coded it in such a way:

```python
foo = cookiejar.get_next_for_processing()
if foo:
    process_in_background(foo, some_callback)
    process_in_background(foo, some_callback)
```

...which you wouldn't do.

**Comment by colin-nolan** [comment]
Okey, thanks - this is not a problem then.
