### ISSUE TITLE
Termination whilst processing leads to cookies in a non-recoverable state 

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#41]
Termination whist processing will leave cookies `in_process` for ever more.

**Comment by Xophmeister** [comment]
It shouldn't: https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/cookiejar/biscuit_tin.py#L158-L165

When Cookie Monster is restarted, any bad state records are cleaned up...at least that's the idea.

**Comment by colin-nolan** [comment]
I didn't know this - good to hear though!

**Comment by Xophmeister** [comment]
Phew! I was beginning to go into a cold sweat 😛
