### ISSUE TITLE
Unofficial baton fork used when testing specific query

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#5]
test-with-baton (https://github.com/wtsi-hgi/test-with-baton) requires a later version of baton than that which currently has the specific query functionality. For now, a compatible (temporary) baton brach has been created that merges the specific query functionality into baton 16.0.1. When specific query is pulled by NPG, the baton branch used in tests should be changed.

Changes required in: https://github.com/wtsi-hgi/cookie-monster/blob/develop/cookiemonster/tests/retriever/source/irods/_settings.py

**Comment by colin-nolan** [comment]
Switched to using `feature/specificquery` branch in `wtsi-hgi/baton`: https://github.com/wtsi-hgi/baton/tree/feature/specificquery.

**Comment by colin-nolan** [comment]
The required functionality now exists within baton's `devel` branch.  Depends now on: https://github.com/wtsi-hgi/docker-baton/issues/2.

**Comment by colin-nolan** [comment]
Fixed in 719ace59368a4ee1ef7074398c273d95131756f0.

**Comment by keithj** [comment]
Just released 0.16.3, which includes specificquery.

**Comment by colin-nolan** [comment]
Thanks @keithj. I've been using 0.16.3-pre until now, which has been working great. I'll switch this to use 0.16.3.
